-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/8/2016 3:59:22 PM
-- Server version: 5.6.30
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO kanban.kb_client(id, clientname, clientid, clientsecret, expires, clientdessecret, desexpires, deletestatus) VALUES
(2, '测试', '1101', 'dadadswdewq2ewdwqdwadsadasd', 1597393163, 'thoqdJpHBlzQ=', 1597393163, '1');
