-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/8/2016 3:59:23 PM
-- Server version: 5.6.30
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO kanban.kb_user(id, username, password, salt) VALUES
(1, 'admin', 'd3c59d25033dbf980d29554025c23a75', '2468');
