-- ----------------------------
-- Table structure for kb_entry
-- ----------------------------
drop table if exists kb_entry;
CREATE TABLE kb_entry (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(50) ,
  reporter int NOT NULL,
  delete_status int DEFAULT 0
  ) ;

-- ----------------------------
-- Table structure for kb_task
-- ----------------------------
drop table if exists kb_task;

CREATE TABLE kb_task (
  id INTEGER  DEFAULT 0 ,
  summary VARCHAR(50) NOT NULL,
  content VARCHAR(50),
  assignee int DEFAULT NULL,
  reporter int DEFAULT NULL,
  entry_id int DEFAULT NULL
  ) ;
